apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rlqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rlqk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rlqk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rlqk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rlqk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-duyq-tenant/rhtap-demo-app/hacbs-test-project-rlqk@sha256:6d084dc7bb7d3a0bd81bb9f9b3c882982b606384511260ed600151f21eec0ab0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
